import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arben
 */
public class ViewProductivity extends javax.swing.JFrame {

    private int user_id = 0;
    private String user_name = "None";
    private int teamProductivityScore = 0;
    private int teamProductivityCount = 0;
    private float teamProductivityAvg;
    public int getUser_id(){
        return this.user_id;
    }
   
    public String getUser_name(){
        return this.user_name;
    }
    
    public void setUser_id(int id){
        this.user_id = id;
    }   
    
    public void setUser_name(String username){
        this.user_name = username;
    }
    public ViewProductivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Teams = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_User = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 233, 233));

        jTable_Teams.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTable_Teams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team", "Score", "Count", "avg productivity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Teams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_TeamsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable_Teams);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Team Productivity");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(682, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable_User.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTable_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "user", "Score", "Count", "avg productivity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UserMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable_User);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_TeamsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TeamsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable_Teams.getModel();
        int selectedRowIndex = jTable_Teams.getSelectedRow();
    }//GEN-LAST:event_jTable_TeamsMouseClicked

    private void jTable_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_UserMouseClicked
    
    public void AddRowToJTable(Object[] dataRow){
        DefaultTableModel model = (DefaultTableModel)jTable_Teams.getModel();
        model.addRow(dataRow);
    }
    
    public void AddRowToJTableUser(Object[] dataRow){
        DefaultTableModel model = (DefaultTableModel)jTable_User.getModel();
        model.addRow(dataRow);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProductivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProductivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProductivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProductivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProductivity().setVisible(true);
//                System.out.println("viewProductivity visible");
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Teams;
    private javax.swing.JTable jTable_User;
    // End of variables declaration//GEN-END:variables
    protected void populateList()
    {
        int thisComplete = 0;
        System.out.println("populateList entered");
        Connection dbconn= DBConnection.connectDB();
        try {
        //objective: get all team members. team members found in user_team as mapping. need to match your team with team_id in user_team
        //SELECT DISTINCT user_id,team_id FROM user_team where team_id in (select team_id from team where user_id = 7);
        //objective: restrict to teams you own
        //SELECT DISTINCT user_id,team_id FROM user_team where team_id in (select team_id from team where user_id = ? and team_owner_id = ?);
        //SELECT DISTINCT user_id,team_id FROM user_team where team_id in (select team_id from team where team_owner_id = ?);
        //objective: get all completed tasks from those users (ignore teams) 
//        
//        SELECT COUNT(completed) from completions where completed_user_id = 4 and completed = 2;
//        SELECT completed_user_id as user_id, completed, count(*) as lateOrNot from completions group by completed;
//        almost
//        PreparedStatement st = (PreparedStatement)
//                dbconn.prepareStatement("CREATE TEMPORARY TABLE users_in_teams SELECT DISTINCT user_id as uid,team_id FROM user_team where team_id in (select team_id from team where team_owner_id = ?)");
//        String user_idStr = Integer.toString(this.user_id);
//        st.setString(1, user_idStr);
//        st.execute();
//        st.close();
//        PreparedStatement st2 = (PreparedStatement)
//                dbconn.prepareStatement("CREATE TEMPORARY TABLE completions SELECT DISTINCT completed_user_id,completed_task_id,completed from user_completed_tasks INNER JOIN users_in_teams on completed_user_id = users_in_teams.uid where completed_user_id = users_in_teams.uid;");
//        st2.execute();
//                st2.close();
//
//         PreparedStatement st3 = (PreparedStatement)
//                dbconn.prepareStatement("CREATE TEMPORARY TABLE late SELECT completed_user_id, COUNT(completed), as tasks_late from completions where completed = 1 GROUP BY completed_user_id;");
//        st3.execute();
//                st3.close();
//
//        PreparedStatement st4 = (PreparedStatement)
//                dbconn.prepareStatement("CREATE TEMPORARY TABLE ontime SELECT completed_user_id, COUNT(completed) as tasks_ontime from completions where completed = 2 GROUP BY completed_user_id;");
//        st4.execute();
//                st4.close();
//
//        PreparedStatement getData = (PreparedStatement)
//                dbconn.prepareStatement("SELECT late.completed_user_id, tasks_late,tasks_ontime from late INNER JOIN ontime ON late.completed_user_id = ontime.completed_user_id group by late.completed_user_id;");
//        
//        ResultSet rs = getData.executeQuery();

        PreparedStatement st = (PreparedStatement)
                        dbconn.prepareStatement("SELECT DISTINCT team_id from user_team WHERE user_id = ?;");
                String user_idStr = Integer.toString(this.user_id);
                st.setString(1, user_idStr);

                st.executeQuery();
                ResultSet rs = st.executeQuery();
        while(rs.next())
        {
            String retrieved_teamID = rs.getString(1);
            System.out.println("team_id in viewProductivity: " + retrieved_teamID);
              PreparedStatement st2 = (PreparedStatement)
                dbconn.prepareStatement("SELECT DISTINCT\n" +
                "task.task_name, task.status, task.task_id,\n" +
                "user_team.user_id, user_team.team_id\n" +
                "FROM user_team\n" +
                "INNER JOIN task\n" +
                "ON task.user_id = user_team.user_id\n" +
                "WHERE team_id = ?" +
                "GROUP BY\n" +
                "task.task_name;" 
                );
              st2.setString(1, retrieved_teamID);
        ResultSet rs2= st2.executeQuery();
        teamProductivityScore = 0;
        teamProductivityCount = 0;
        
       
        while(rs2.next())
        {
//            System.out.println("table in viewProductivity: " + rs2.getString(1) + rs2.getString(2) + rs2.getString(3));
            
            
//            String retrieved_userID = rs.getString(1);
//            System.out.println("In ViewProductivity: getUserID: " + retrieved_userID);

            PreparedStatement getCompleted = (PreparedStatement)
                    dbconn.prepareStatement("SELECT completed FROM user_completed_tasks WHERE completed_user_id = ? and completed_task_id = ?;");
//            System.out.println("getString(4): "+ rs2.getString(4));
//            System.out.println("getString(3): "+ rs2.getString(3));
            
            getCompleted.setString(1, rs2.getString(4));
            getCompleted.setString(2, rs2.getString(3));
//            System.out.println(getCompleted);
            ResultSet completedResult = getCompleted.executeQuery();
            
            boolean check = false;
            
            while (completedResult.next())
            {
                thisComplete = Integer.parseInt(completedResult.getString(1));
                check = true;
//                System.out.println("completedResult: " + completedResult.getString(1));         
            }
            
           if (!check){
               thisComplete = 2;
           }

           teamProductivityScore+=thisComplete;
           teamProductivityCount+=1;
            completedResult.close();
//            ResultSet retrievedUserNameSet = getUserName.executeQuery();
//            retrievedUserNameSet.next();
//            String retrievedUserName = retrievedUserNameSet.getString(1);
////            retrievedUserNameSet.close();
////            
//            String tasks_late = rs2.getString(2);
//            
//            String tasks_ontime = rs2.getString(3);
//            
//            float usr_avg_productivity = calcProductivity(tasks_late, tasks_ontime);
            
        }
        rs2.close();
        
        // get team_name from team id
            PreparedStatement getTeamName = (PreparedStatement)
            dbconn.prepareStatement("SELECT team_name FROM team WHERE team_id = ?;");      
            getTeamName.setString(1, retrieved_teamID);
//            System.out.println(getCompleted);
            ResultSet teamName = getTeamName.executeQuery();
            String sTeamName = "";
            while (teamName.next())
            {
                sTeamName = teamName.getString(1);        
            }
        // end get team_name from team id
            //System.out.println("teamProductivityScore: " + teamProductivityScore + ", teamProductivityCount: " + teamProductivityCount);
            AddRowToJTable(new Object[]{
                            sTeamName,
                            teamProductivityScore,
                            teamProductivityCount,
                            (float)teamProductivityScore / teamProductivityCount
                            });
        }
        
        rs.close();
//        getData.close();
        

        /* Populate User_Productivity table*/
        PreparedStatement st_user = (PreparedStatement)
        dbconn.prepareStatement("Select DISTINCT user_id from user;");
        ResultSet rs_user= st_user.executeQuery();
        while(rs_user.next())
        {
            thisComplete = 0;
            PreparedStatement st2_user = (PreparedStatement)
            dbconn.prepareStatement("SELECT DISTINCT\n" +
                                    "task.task_name, task.task_id,\n" +
                                    "user_team.user_id, user_team.team_id \n" +
                                    "FROM user_team\n" +
                                    "INNER JOIN task\n" +
                                            "ON task.user_id = user_team.user_id\n" +
                                    "WHERE user_team.user_id = ?\n" +
                                    "GROUP BY task.task_name;"
            );
            st2_user.setString(1, rs_user.getString(1));
            ResultSet rs2_user= st2_user.executeQuery();
            teamProductivityScore = 0;
            teamProductivityCount = 0;
            while(rs2_user.next())
            {
                PreparedStatement getCompleted_user = (PreparedStatement)
                    dbconn.prepareStatement("SELECT completed FROM user_completed_tasks WHERE completed_user_id = ? and completed_task_id = ?;");
                    getCompleted_user.setString(1, rs2_user.getString(3));
                    getCompleted_user.setString(2, rs2_user.getString(2));
                    ResultSet completedResult_user = getCompleted_user.executeQuery();

                    boolean check_user = false;

                    while (completedResult_user.next())
                    {
                        thisComplete = Integer.parseInt(completedResult_user.getString(1));
                        check_user = true;
        //                System.out.println("completedResult: " + completedResult.getString(1));         
                    }
                    completedResult_user.close();
                    if (!check_user){
                        thisComplete = 2;
                    }
                    
                    teamProductivityScore+=thisComplete;
                    teamProductivityCount+=1;
                /*
              
                */
            }

            rs2_user.close();

            // do something here
            // get team_name from team id
            PreparedStatement getUserName = (PreparedStatement)
            dbconn.prepareStatement("SELECT username FROM user WHERE user_id = ?;");      
            getUserName.setString(1, rs_user.getString(1));
//            System.out.println(getCompleted);
            ResultSet userName = getUserName.executeQuery();
            String sUserName = "";
            while (userName.next())
            {
                sUserName = userName.getString(1);        
            }
            // end get team_name from team id
            AddRowToJTableUser(new Object[]{
                sUserName,
                teamProductivityScore,
                teamProductivityCount,
                (float)teamProductivityScore / teamProductivityCount
                    
                });
        }
        rs_user.close();
                /* End Populate User_Productivity table*/
                } catch (Exception ex) {
                     Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

    private void changeCellColor(JTable table, int column_index) {
        table.getColumnModel().getColumn(column_index).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                int prod_avg = Integer.parseInt(table.getValueAt(row, column_index).toString());
                final Color best = new Color(153,255,153);
                final Color medium = new Color(255,255,102);
                final Color good = new Color(102,204,255);
                final Color poor = new Color(255,153,153);
                if (prod_avg < 1.25) {
                    c.setBackground(poor);
                } else if(prod_avg >= 1.25 & prod_avg <1.5) {
                    c.setBackground(medium);
                }else if(prod_avg >=1.5 & prod_avg <1.75) {
                    c.setBackground(good);
                }else if(prod_avg >1.75) {
                    c.setBackground(best);
                }
                return c;
            }
        });
    }

    private float calcProductivity(String tasks_late, String tasks_ontime) {
        int tLate = Integer.parseInt(tasks_late);
        int tOnTime = Integer.parseInt(tasks_ontime);
        float avg = ((1*tLate)+(2*tOnTime))/(float)(tLate+tOnTime);
        return avg;
    }


}
class MyTableCellRenderer3 extends DefaultTableCellRenderer {
        @Override
        public Color getBackground() {
            return super.getBackground();
        }
  }